package sammyne:helloworld@1.0.0;

interface greeter {
    use types.{hello-request, hello-reply};

    say-hello: func(req: hello-request) -> hello-reply;
}

interface types {
    record hello-request {
        name: string,
    }

    record hello-reply {
        message: string,
    }
}

/// An example world for the component to target.
world helloworld {
    export greeter;
}

// 作为依赖库被使用
world helloworld-lib {
    import greeter;
}
