package sammyne:helloworld@1.0.0;

interface greeter {
    use types.{context, hello-request, hello-reply};

    say-hello: func(ctx: borrow<context>, req: hello-request) -> hello-reply;
}

interface types {
    record hello-request {
        name: string,
    }

    record hello-reply {
        message: string,
    }

    resource context {
        request-id: func() -> s64;
        
        greet: func(name: string) -> string;
    }
}

/// An example world for the component to target.
world helloworld {
    export greeter;
}
